### PR TITLE
Fix #55: Avoid Sprockets deprecation messages

### LINKED ISSUE #55: Sprockets register_engine deprecated
Hello there, I'm using the `skim` gem to convert `hamljs` templates to slim using the `.jst.skim` extension. It works perfectly but Sprockets as of version 3.7.0 deprecated the `register_engine` call in favor of a different approach using `register_mime_type` and either `register_compressor` or `register_transformer`.

This is the exact error I'm getting:

```
DEPRECATION WARNING: Sprockets method `register_engine` is deprecated.
Please register a mime type using `register_mime_type` then
use `register_compressor` or `register_transformer`.
https://github.com/rails/sprockets/blob/master/guides/extending_sprockets.md#supporting-all-versions-of-sprockets-in-processors
 (called from <top (required)> at /Users/myusername/.rvm/gems/ruby-2.3.0/gems/skim-0.10.0/lib/skim/sprockets.rb:3)
```

Replicating this issue should be simple.

In a fresh Rails app,

**Gemfile**

    gem 'skim'
    gem 'sprockets', '>= 3.7.0'

Run the `bundle` or `bundle install` command
Restart rails server (<kbd>ctrl</kbd>+<kbd>c</kbd> to stop `rails s` to start)

The message should appear when starting the server, if not try creating a template

### PR DESCRIPTION
**Pull request by zamakkat**

### CODE REVIEW

**Comment by docstun** [comment]
Would love to see that deprecation warning gone, too 👍

**Comment by BrentWheeldon** [comment]
I've love to see this merged, too 👍

**Comment by BrentWheeldon** [comment]
I've actually been digging in on this and it seems like this doesn't work? I'm getting this error when I run `rake assets:precompile`:

```
NoMethodError: undefined method `call' for Skim::Template:Class
Did you mean?  caller
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/loader.rb:60:in `block in load'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/loader.rb:44:in `load'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:47:in `load'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/bundle.rb:23:in `block in call'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/utils.rb:196:in `dfs'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/bundle.rb:24:in `call'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:75:in `call_processor'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/processor_utils.rb:56:in `call_processors'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/loader.rb:60:in `block in load'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/loader.rb:44:in `load'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/cached_environment.rb:47:in `load'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/base.rb:66:in `find_asset'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/manifest.rb:134:in `block in find'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/manifest.rb:133:in `each'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/manifest.rb:133:in `find'
/Users/me/.rvm/gems/ruby-2.3.3@project/gems/sprockets-3.7.0/lib/sprockets/manifest.rb:185:in `compile'
```

I'm using sprockets 3.7.0.

Are there further changes required to remove this deprecation warning?

**Comment by zamakkat** [comment]
Yeah I did notice the build was failing but didn't have the time to look into the details of why it was failing. Will do so soon-ish if no one does it before me.

**Comment by amseledka** [comment]
Are there any updates coming on this one? 🙏

**Comment by DonSchado** [comment]
@zamakkat @amseledka @BrentWheeldon @docstun @iBublik @StanisLove pls checkout the mentioned PR (https://github.com/appjudo/skim/pull/61). 
I know it's an older issue, but maybe this is still relevant to you. 

👋

**Comment by svicalifornia** [comment]
Thanks for the contribution! We merged #61 instead, which should resolve the same issue. We also released that change as part of Skim 0.11.0. Please give it a try.

**Pull request closed without merging**
